export const environment = {
    production: false,
    streamingInfoApiBaseUrl: 
    'https://streaming-availability.p.rapidapi.com/search/title',
    XRapidAPIHostHeaderName: 'X-RapidAPI-Host',
    RapidAPIHostHeaderValue: 'streaming-availability.p.rapidapi.com',
    XRapidAPIKeyHeaderName: 'X-RapidAPI-Key',
    XRapidAPIKeyHeaderValue: 
    'e7a0843102msh0cc74ffa918873cp19c5a5jsn39e99b27184d',
    countries: [
        { "code": "ae", "name": "United Emirates" },
        { "code": "ar", "name": "Argentina" },
        { "code": "at", "name": "Austria" },
        { "code": "au", "name": "Australia" },
        { "code": "az", "name": "Azerbaijan" },
        { "code": "be", "name": "Belgium" },
        { "code": "bg", "name": "Bulgaria" },
        { "code": "br", "name": "Brazil" },
        { "code": "ca", "name": "Canada" },
        { "code": "ch", "name": "Switzerland" },
        { "code": "cl", "name": "Chile" },
        { "code": "co", "name": "Colombia" },
        { "code": "cy", "name": "Cyprus" },
        { "code": "cz", "name": "Czech Republic" },
        { "code": "de", "name": "Germany" },
        { "code": "dk", "name": "Denmark" },
        { "code": "ec", "name": "Ecuador" },
        { "code": "ee", "name": "Estonia" },
        { "code": "es", "name": "Spain" },
        { "code": "fi", "name": "Finland" },
        { "code": "fr", "name": "France" },
        { "code": "gb", "name": "United Kingdom" },
        { "code": "gr", "name": "Greece" },
        { "code": "hk", "name": "Hong Kong" },
        { "code": "hr", "name": "Croatia" },
        { "code": "hu", "name": "Hungary" },
        { "code": "id", "name": "Indonesia" },
        { "code": "ie", "name": "Ireland" },
        { "code": "il", "name": "Israel" },
        { "code": "in", "name": "India" },
        { "code": "is", "name": "Iceland" },
        { "code": "it", "name": "Italy" },
        { "code": "jp", "name": "Japan" },
        { "code": "kr", "name": "South Korea" },
        { "code": "lt", "name": "Lithuania" },
        { "code": "md", "name": "Moldova" },
        { "code": "mk", "name": "North Macedonia" },
        { "code": "mx", "name": "Mexico" },
        { "code": "my", "name": "Malaysia" },
        { "code": "nl", "name": "Netherlands" },
        { "code": "no", "name": "Norway" },
        { "code": "nz", "name": "New Zealand" },
        { "code": "pa", "name": "Panama" },
        { "code": "pe", "name": "Peru" },
        { "code": "ph", "name": "Philippines" },
        { "code": "pl", "name": "Poland" },
        { "code": "pt", "name": "Portugal" },
        { "code": "ro", "name": "Romania" },
        { "code": "rs", "name": "Serbia" },
        { "code": "ru", "name": "Russia" },
        { "code": "se", "name": "Sweden" },
        { "code": "sg", "name": "Singapore" },
        { "code": "th", "name": "Thailand" },
        { "code": "tr", "name": "Turkey" },
        { "code": "ua", "name": "Ukraine" },
        { "code": "us", "name": "United States" },
        { "code": "vn", "name": "Vietnam" },
        { "code": "za", "name": "South Africa" }
      ]
};